version: '3.8'

services:
  # Our monorepo app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # For Next.js (web)
      - "8081:8081" # For Expo Metro bundler (mobile)
    volumes:
      - .:/app
      - /app/node_modules # Isolate node_modules
    environment:
      - NODE_ENV=development
      # Pass Supabase anon key and URL to the app
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_SUPABASE_URL=${SUPABASE_URL}
    depends_on:
      - db

  # Supabase local development stack
  db:
    image: supabase/postgres:15.1.0.118
    ports:
      - "54322:5432"
    volumes:
      - ./supabase/db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Add other Supabase services like auth, storage, etc. as needed
  # For now, we'll keep it simple with just the database.

volumes:
  db_data:
